# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2417735326be051f20dd612d4257b6522471cfb38824cc5bc23221d38690fc8d5124a2f5f7a7c8ea56192999d970ecc8379e0aba2685ffabc74a3a2fe4f8c95e

test:
  secret_key_base: a898fc17fb66d72b2bc0688cd912b5ed7177f6ca5b68c9da8149cdd5d68c4cb73e4d05aaf26400079a742e3da49ace22bfef84c558fc984694cfe16ba4999e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
